name: bphl
channels:
  - anaconda
  - pytorch
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - mafft==7.520
  - biopython==1.81
  - ipywidgets==8.1.0
  - jupyter==1.0.0
  - mash==2.3
  - matplotlib-inline==0.1.6
  - nbconvert-core==7.16.4
  - nbconvert-pandoc==7.16.4
  - pip==23.2.1
  - python==3.10.12
  - yaml==0.2.5
  - cogent3==2023.9.22a1
  - ete3==3.1.3
  - ipykernel==6.29.4
  - matplotlib==3.9.3
  - nbformat==5.9.2
  - nbsphinx==0.9.3
  - notebook==7.0.6
  - notebook-shim==0.2.3
  - numpy==1.23.5
  - numpydoc==1.6.0
  - pandas==2.2.2
  - plotly==5.18.0
  - pysam==0.22.1
  - pytest==8.3.2
  - pyyaml==6.0.2
  - regex==2023.12.25
  - scikit-learn==1.3.2
  - seaborn==0.13.2
  - statsmodels==0.14.3
  - pip:
    - kaleido==0.2.1
    - nb-offline-convert==0.1.1
    - nbclient==0.8.0
    - nbconvert==7.8.0
    - tn93==1.2.0
    - umap==0.1.1
    - umap-learn==0.5.4
    - staphb-toolkit==2.0.1
    - ipython==8.12.3
